Arguments: 
  /usr/local/bin/node /opt/yarn-v1.5.1/bin/yarn.js run debug

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.5.1

Node version: 
  8.10.0

Platform: 
  linux x64

npm manifest: 
  {
      "name": "server",
      "version": "0.0.0",
      "scripts": {
        "postinstall": "tsc -p ./src",
        "watch": "tsc -w -p ./src",
        "debug": "nodemon --watch ./dist --inspect=0.0.0.0:5858 --nolazy ./dist/index.js",
        "docker-debug": "docker-compose up",
        "start": "node ./dist/index.js"
      },
      "devDependencies": {
        "@types/node": "^6.0.50",
        "typescript": "^2.3.2",
        "nodemon": "^1.11.0"
      },
      "main": "./dist/index.js"
    }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Command failed.
  Exit code: 127
  Command: sh
  Arguments: -c nodemon --watch ./dist --inspect=0.0.0.0:5858 --nolazy ./dist/index.js
  Directory: /wwwroot/api
  Output:
  
      at ProcessTermError.MessageError (/opt/yarn-v1.5.1/lib/cli.js:186:110)
      at new ProcessTermError (/opt/yarn-v1.5.1/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/opt/yarn-v1.5.1/lib/cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
